Test full build.

diff --git a/.github/workflows/build-and-publish.yml b/.github/workflows/build-and-publish.yml
--- a/.github/workflows/build-and-publish.yml
+++ b/.github/workflows/build-and-publish.yml
@@ -20,19 +20,19 @@ jobs:
     - uses: actions/checkout@v2
     
     - name: Fetch all history and tags (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       run: |
         git fetch --unshallow --prune
 
     - name: Install GitVersion (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       uses: gittools/actions/gitversion/setup@v0.9.10
       with:
         versionSpec: '5.x'
         includePrerelease: false
   
     - name: Determine Version (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       id: gitversion
       uses: gittools/actions/gitversion/execute@v0.9.10
       with:
@@ -41,7 +41,7 @@ jobs:
         additionalArguments: '-ensureassemblyinfo'
 
     - name: Display Version (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: powershell
       run: |
         Write-Output "==============================================================================================================================================="
@@ -54,7 +54,7 @@ jobs:
         dotnet-version: 7.0.x
 
     - name: Patch BuildDateAttribute (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: powershell
       run: |
         Write-Output "==============================================================================================================================================="
@@ -71,7 +71,7 @@ jobs:
         Write-Output "==============================================================================================================================================="
 
     - name: Patch CommitIdAttribute (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: powershell
       run: |
         Write-Output "==============================================================================================================================================="
@@ -88,15 +88,15 @@ jobs:
         Write-Output "==============================================================================================================================================="
 
     - name: Build HostsManager (Check)
-      if: github.ref != 'refs/heads/main'
+      #if: github.ref != 'refs/heads/main'
       run: dotnet build "./src" --configuration Release
     
     - name: Build HostsManager with Version (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       run: dotnet build "./src" --configuration Release -p:Version=${{ steps.gitversion.outputs.MajorMinorPatch }} -p:FileVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
 
     - name: Decode Code-Signing Pfx
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       working-directory: "./src"
       shell: powershell
       run: |
@@ -105,7 +105,7 @@ jobs:
         [IO.File]::WriteAllBytes("$certificatePath", $pfx_cert_byte)
 
     - name: Sign Application Files (Post Build)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       working-directory: "./src"
       shell: powershell
       run: |
@@ -120,19 +120,19 @@ jobs:
         }
         
     - name: Install Inno Setup (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: cmd
       run: |
         choco install innosetup
 
     - name: Build Installer (Publish)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       working-directory: "./src/${{ env.INSTALLER_DIR }}"
       run: |
         iscc.exe EM.HostsManager.Installer.iss /DInstallerVersion=${{ steps.gitversion.outputs.MajorMinorPatch }}
 
     - name: Sign Installer (Post Build)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       working-directory: "./src"
       shell: powershell
       run: |
@@ -147,14 +147,14 @@ jobs:
         }
 
     - name: Clean up (Code Signing Pfx)
-      if: (github.ref == 'refs/heads/main' && success() || failure())
+      #if: (github.ref == 'refs/heads/main' && success() || failure())
       shell: powershell
       working-directory: "./src"
       continue-on-error: true
       run: Remove-Item -Verbose -Path ${{ env.CERT_FILENAME }}
 
     - name: Copy Build Files (1 of 3)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: cmd
       working-directory: "./src"
       run: |
@@ -162,7 +162,7 @@ jobs:
         copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\*.*" "Binaries"
 
     - name: Copy Build Files (2 of 3)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: cmd
       working-directory: "./src"
       run: |
@@ -174,7 +174,7 @@ jobs:
         copy "${{ env.APP_DIR }}\bin\${{ env.BUILD_CONFIG }}\${{ env.DOTNET_VER }}\EM.HostsManager.App.runtimeconfig.json" "Binaries\Deploy"
 
     - name: Copy Build Files (3 of 3)
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       shell: cmd
       working-directory: "./src"
       run: |
@@ -194,7 +194,7 @@ jobs:
     #    git push --force --tags origin
 
     - name: Publish build artifacts
-      if: github.ref == 'refs/heads/main'
+      #if: github.ref == 'refs/heads/main'
       uses: actions/upload-artifact@v3
       with:
         name: EM.HostsManager-${{steps.gitversion.outputs.MajorMinorPatch}}
